<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Emgu.CV" Version="4.13.0.5924" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="captures\52871e38-3b62-4815-9ddb-e2bfd2cc93a9\manifest.json" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="captures\" />
    </ItemGroup>

</Project>
